accounts:
  - name: alice
    coins: ["100000000uatom", "100000000000000000000aepix"]
  - name: bob
    coins: ["5000000000000aepix"]
validator:
  name: alice
  staked: "100000000000000000000aepix"
faucet:
  name: bob 
  coins: ["10aepix"]
build:
  binary: "epixd"
init:
  home: "$HOME/.epixd"
  app:
    evm-rpc:
      address: "0.0.0.0:8545"     # change the JSON-RPC address and port
      ws-address: "0.0.0.0:8546"  # change the JSON-RPC websocket address and port
genesis:
  chain_id: "epixd_4243-1"
  app_state:
    staking:
      params:
        bond_denom: "aepix"
    mint:
      params:
        mint_denom: "aepix"
    crisis:
      constant_fee:
        denom: "aepix"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "aepix"
    evm:
      params:
        evm_denom: "aepix"
